stages:
  - build
  - deploy

variables:
  IMAGE_TAG: registry.gitlab.com/thigas-group/tscontrol-web:homol

build_image:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - homol

deploy_homologacao:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "Iniciando deploy no servidor $SERVER_IP..."
    # Conecta no servidor, baixa a imagem nova e roda o docker-compose
    # Ajuste o caminho /home/ubuntu/financas-api se o seu docker-compose.homol.yml estiver em outra pasta!
    - ssh $SERVER_USER@$SERVER_IP "docker pull $IMAGE_TAG && cd /home/ubuntu/financas-api && docker-compose -f docker-compose.homol.yml up -d tscontrol-web"
  only:
    - homol