image: maven:3.9.6-eclipse-temurin-21-alpine

cache:
  paths:
    - .m2/repository

stages:
  - build
  - test
  - dockerize
  - deploy-homol

build_api:
  stage: build
  script:
    - echo "Compilando o XP Finance com Java 21..."
    - mvn clean compile -DskipTests -Dmaven.repo.local=.m2/repository

test_api:
  stage: test
  script:
    - echo "Rodando bateria de testes do XP Finance..."
    - mvn test -DskipTests -Dmaven.repo.local=.m2/repository

build_imagem_docker:
  stage: dockerize
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "Construindo a imagem Docker xpfinance-api:homol..."
    - docker build -t xpfinance-api:homol .

deploy_homologacao:
  stage: deploy-homol
  image: docker:24.0.5
  script:
    - echo "Iniciando o Deploy do XP Finance em Homologação..."
    - docker compose -f docker-compose.homol.yml up -d --build
    - echo "Limpando imagens antigas para não lotar o HD"
    - docker image prune -f
    - echo "Deploy concluído!"
  tags:
    - shell
  environment:
    name: homologacao
    url: http://localhost:8081